services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ${ENVIRONMENT}
    container_name: nodejs-backend
    ports:
      - "3000:${PORT}"
    environment:
      - PORT=${PORT}
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src:ro
      - ../logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
